apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "collective-ams.fullname" . }}-dbmigrate"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{ include "collective-ams.fullname" . }}-dbmigrate"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      imagePullSecrets:
      - name: {{ .Values.imagePullSecret | quote }}
      restartPolicy: Never
      containers:
      - name: pre-install-dbmigrate
        image: "{{ .Values.repository }}/{{ .Values.backend.image.name }}:{{ .Values.backend.image.tag }}"
        command: ["yarn", "run", "prisma-deploy"]
        env:
          - name: DATABASE_ADAPTER
            value: {{ .Values.backend.env.DATABASE_ADAPTER | default "prisma_postgresql" }} 
          - name: DATABASE_URL
            value: {{ .Values.backend.env.DATABASE_URL }}
          - name: SESSION_SECRET
            value: 'avalueforsomethingstowork'